import {
  LDClientContext,
  LDLogger,
  subsystem,
  VoidFunction,
} from '@launchdarkly/js-sdk-common';

import {
  integrations,
  LDProxyOptions,
  LDTLSOptions,
  subsystems,
} from '@launchdarkly/js-server-sdk-common';

type Hook = integrations.Hook;

import { LDPlugin } from './LDPlugin';

/**
 * LaunchDarkly initialization options for the synchronous server-side Node SDK.
 *
 * This SDK does not support daemon mode (`useLdd`), persistent feature stores
 * (`featureStore`), or big segments (`bigSegments`).
 */
export interface LDOptions {
  /**
   * The base URI for the LaunchDarkly server.
   *
   * Most users should use the default value.
   */
  baseUri?: string;

  /**
   * The base URI for the LaunchDarkly streaming server.
   *
   * Most users should use the default value.
   */
  streamUri?: string;

  /**
   * The base URI for the LaunchDarkly events server.
   *
   * Most users should use the default value.
   */
  eventsUri?: string;

  /**
   * The connection timeout, in seconds.
   */
  timeout?: number;

  /**
   * The capacity of the analytics events queue.
   *
   * The client buffers up to this many events in memory before flushing. If the capacity is
   * exceeded before the buffer is flushed, events will be discarded.
   */
  capacity?: number;

  /**
   * Configures a logger for warnings and errors generated by the SDK.
   *
   * The logger can be any object that conforms to the {@link LDLogger} interface.
   */
  logger?: LDLogger;

  /**
   * A component that obtains feature flag data and puts it in the feature store.
   */
  updateProcessor?:
    | object
    | ((
        clientContext: LDClientContext,
        dataSourceUpdates: subsystems.LDDataSourceUpdates,
        initSuccessHandler: VoidFunction,
        errorHandler?: (e: Error) => void,
      ) => subsystem.LDStreamProcessor);

  /**
   * The interval in between flushes of the analytics events queue, in seconds.
   */
  flushInterval?: number;

  /**
   * The time between polling requests, in seconds. Ignored in streaming mode.
   */
  pollInterval?: number;

  /**
   * Allows you to specify configuration for an optional HTTP proxy.
   */
  proxyOptions?: LDProxyOptions;

  /**
   * Whether the client should be initialized in offline mode.
   */
  offline?: boolean;

  /**
   * Whether streaming mode should be used to receive flag updates.
   *
   * This is true by default. If you set it to false, the client will use polling.
   * Streaming should only be disabled on the advice of LaunchDarkly support.
   */
  stream?: boolean;

  /**
   * Sets the initial reconnect delay for the streaming connection, in seconds.
   *
   * The streaming service uses a backoff algorithm (with jitter) every time the connection needs
   * to be reestablished. The delay for the first reconnection will start near this value, and then
   * increase exponentially for any subsequent connection failures.
   *
   * The default value is 1.
   */
  streamInitialReconnectDelay?: number;

  /**
   * Whether to send analytics events back to LaunchDarkly. By default, this is true.
   */
  sendEvents?: boolean;

  /**
   * Whether all context attributes (except the context key) should be marked as private, and
   * not sent to LaunchDarkly.
   *
   * By default, this is false.
   */
  allAttributesPrivate?: boolean;

  /**
   * The names of any context attributes that should be marked as private, and not sent
   * to LaunchDarkly.
   */
  privateAttributes?: Array<string>;

  /**
   * The number of context keys that the event processor can remember at any one time,
   * so that duplicate context details will not be sent in analytics events.
   *
   * Defaults to 1000.
   */
  contextKeysCapacity?: number;

  /**
   * The interval (in seconds) at which the event processor will reset its set of
   * known context keys.
   *
   * Defaults to 300.
   */
  contextKeysFlushInterval?: number;

  /**
   * Additional parameters to pass to the Node HTTPS API for secure requests.
   */
  tlsParams?: LDTLSOptions;

  /**
   * Set to true to opt out of sending diagnostics data.
   */
  diagnosticOptOut?: boolean;

  /**
   * The interval at which periodic diagnostic data is sent, in seconds.
   *
   * The default is 900 (every 15 minutes) and the minimum value is 60 (every minute).
   */
  diagnosticRecordingInterval?: number;

  /**
   * For use by wrapper libraries to set an identifying name for the wrapper being used.
   */
  wrapperName?: string;

  /**
   * For use by wrapper libraries to report the version of the library in use.
   */
  wrapperVersion?: string;

  /**
   * Information about the application where the LaunchDarkly SDK is running.
   */
  application?: {
    id?: string;
    version?: string;
    name?: string;
    versionName?: string;
  };

  /**
   * Payload filter key for filtered environments.
   */
  payloadFilterKey?: string;

  /**
   * Initial set of hooks for the client.
   *
   * Hooks provide entrypoints which allow for observation of SDK functions.
   */
  hooks?: Hook[];

  /**
   * Set to true to opt in to compressing event payloads if the SDK supports it.
   *
   * Defaults to false.
   */
  enableEventCompression?: boolean;

  /**
   * A list of plugins to be used with the SDK.
   *
   * Plugin support is currently experimental and subject to change.
   */
  plugins?: LDPlugin[];
}
